FROM ubuntu:22.04
SHELL ["/bin/bash", "-c"]
#https://gist.github.com/nhtua/2d294f276dc1e110a7ac14d69c37904f
RUN apt-get update; apt-get install -y default-jdk; apt-get -y install default-jre pulseaudio
RUN apt-get install -y wget; wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
RUN apt-get install -y python3 python3-pip
RUN python3 -m pip install flask
ENV ANDROID_HOME=/opt/androidsdk
RUN mkdir -p $ANDROID_HOME
RUN mkdir $ANDROID_HOME/cmdline-tools
RUN apt-get install unzip -y && unzip commandlinetools-linux-9477386_latest.zip  -d $ANDROID_HOME/cmdline-tools

RUN echo "export ANDROID_HOME=$ANDROID_HOME" >> ~/.bashrc;echo 'export SDK=$ANDROID_HOME' >> ~/.bashrc;echo 'export PATH=$SDK/emulator:$SDK/tools:$SDK/cmdline-tools/latest/bin:$SDK/platform-tools:$PATH' >> ~/.bashrc
RUN source ~/.bashrc

ENV PATH="$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools"
RUN mkdir /opt/androidsdk/cmdline-tools/latest
RUN mv -T /opt/androidsdk/cmdline-tools/cmdline-tools /opt/androidsdk/cmdline-tools/latest

COPY emulator_dist.tar.gz /opt/androidsdk/
RUN cd /opt/androidsdk/  && tar xvf ./emulator_dist.tar.gz
COPY package.xml /opt/androidsdk/emulator/

RUN yes | sdkmanager "platform-tools" "platforms;android-34" 
RUN yes | sdkmanager "system-images;android-34;default;arm64-v8a"

RUN apt-get install -y libpcre2-dev

RUN avdmanager create avd -n dev -d pixel_6 -k "system-images;android-34;default;arm64-v8a"

RUN echo "Vulkan = off" >> ~/.android/advancedFeatures.ini
RUN echo "GLDirectMem = on" >> ~/.android/advancedFeatures.ini
RUN rm /opt/androidsdk/emulator/crashpad_handler #FUCK OFF

COPY avd.tar.gz /root/.android/
RUN cd /root/.android && tar xvf avd.tar.gz && rm avd.tar.gz
